#!/bin/bash
#PBS -S /bin/bash
#PBS -l walltime=36:00:00
#PBS -l nodes=8:ppn=8
#PBS -m e
#PBS -j oe
#PBS -q wenjun
#PBS -o 1ubq_pbs.out
#PBS -N 1ubq
#
# Change to job submission directory
#


cd $PBS_O_WORKDIR
#
# load namd via module

. $MODULESHOME/init/bash
module load namd/2.7b2-IB
#module load namd/2.7b1-IB
#
# Set number of processors to number requested from PBS
#
NP=`cat $PBS_NODEFILE | wc -l`
echo "NAMDHOME = "$NAMDHOME
#
# construct namd nodes file from $PBS_NODEFILE
#
export NODELIST=tmp.$$
echo "group main" > $NODELIST
NODES=`cat $PBS_NODEFILE`
for node in $NODES ; do
   echo "host "$node >> $NODELIST
done

PROT_PATH=/panasas/scratch/tekpinar/1ubq/work_1UBQ_ss10/MD_protein_in_water
WAT_PATH=/panasas/scratch/tekpinar/1ubq/work_1UBQ_ss10/MD_water

#Initially, lets do protein+water. 
#
echo "Minimization step for 'protein+water':"
CURRENTDIR=${PROT_PATH}/min/
date
INFILE=$CURRENTDIR/min.namd
charmrun $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
date

echo "Equillibration step for 'protein+water':"
CURRENTDIR=${PROT_PATH}/pre-equil/
date
INFILE=$CURRENTDIR/equil.namd
charmrun $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
date

echo "Production step for 'protein+water':"
CURRENTDIR=${PROT_PATH}/prod/
date
INFILE=$CURRENTDIR/equil.namd
charmrun $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
date

#Now, lets do just water simulation. 
#
echo "Minimization step for just water box:"
CURRENTDIR=${WAT_PATH}/min/
date
INFILE=$CURRENTDIR/min.namd
charmrun $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
date

echo "Equillibration step for just water box:"
CURRENTDIR=${WAT_PATH}/pre-equil/
date
INFILE=$CURRENTDIR/equil.namd
charmrun $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
date

echo "Production step for just water box:"
CURRENTDIR=${WAT_PATH}/prod/
date
INFILE=$CURRENTDIR/equil.namd
charmrun $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
date


echo "Molecular dynamic simulation finished!"
\rm $NODELIST