#PBS -S /bin/bash
#PBS -l walltime=72:00:00
#PBS -l nodes=1:IB3:ppn=12
#PBS -m e
#PBS -j oe
#PBS -o hmglbn_waxs_gpu.out
#PBS -N hmglbn_waxs_gpu
#PBS –q gpu

#
# Change to job submission directory
#

export CONV_RSH=ssh

cd $PBS_O_WORKDIR
#
# load namd via module

. $MODULESHOME/init/bash
module load namd/2.8-CUDA

#
# Set number of processors to number requested from PBS
#
NP=`cat $PBS_NODEFILE | wc -l`
echo "NAMDHOME = "$NAMDHOME
#
# construct namd nodes file from $PBS_NODEFILE
#
export NODELIST=tmp.$$
echo "group main" > $NODELIST
NODES=`cat $PBS_NODEFILE`
for node in $NODES ; do
   echo "host "$node >> $NODELIST
done

PROTEIN=1BBB
SHELL_THICKNESS=7
NAME_WORK_DIR=work_${PROTEIN}
PATH_WORK_DIR=/panasas/scratch/tekpinar/hemoglobin/${NAME_WORK_DIR}
PROT_PATH=${PATH_WORK_DIR}/MD_protein_in_water
WAT_PATH=${PATH_WORK_DIR}/MD_water

#Produce MD simulation parameters(or configuration file)!
#echo "q_min           =       0.01
#q_incr          =       0.01
#q_max           =       2.00
#n_sphere_points =       1500

#prm_file        =       ${HOME}/toppar/par_all27_prot_lipid_more.prm
#pdb_file        =       ${PROTEIN}.pdb
#psf_file        =       ${PROTEIN}.psf

#work_directory  =       ${NAME_WORK_DIR}
#temperature     =       277
#shell_thickness =       ${SHELL_THICKNESS}

# MD step size is 2 fs.

#n_min_steps                     =       1000
#n_pre-equilibration_steps       =       100000
#n_production_run_steps          =       1000000
#n_steps_bet_snapshots           =       500
#n_processors                    =       8">xs.cfg

#echo "Producing required files and folders!"
#./run_pre_process xs.cfg

#Initially, lets do protein+water. 
#
#echo "Minimization step for 'protein+water':"
#CURRENTDIR=${PROT_PATH}/min
#date
#INFILE=$CURRENTDIR/min.namd
#charmrun ++remote-shell ssh ++verbose $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST  $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
#date

#echo "Equillibration step for 'protein+water':"
#CURRENTDIR=${PROT_PATH}/pre-equil
#date
#INFILE=$CURRENTDIR/equil.namd
#charmrun ++remote-shell ssh ++verbose $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE  >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
#date

echo "Production step for 'protein+water':"
CURRENTDIR=${PROT_PATH}/prod
date
INFILE=$CURRENTDIR/equil.namd
./charmrun ++local +p12 $NAMDHOME/namd2 +idlepoll <$INFILE  >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
#charmrun ++remote-shell ssh ++verbose $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE  >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
date

#Now, lets do just water simulation. 
#
#echo "Minimization step for just water box:"
#CURRENTDIR=${WAT_PATH}/min
#date
#INFILE=$CURRENTDIR/min.namd
#charmrun ++remote-shell ssh ++verbose $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE  >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
#date

#echo "Equillibration step for just water box:"
#CURRENTDIR=${WAT_PATH}/pre-equil
#date
#INFILE=$CURRENTDIR/equil.namd
#charmrun ++remote-shell ssh ++verbose $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE  >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
#date

#echo "Production step for just water box:"
#CURRENTDIR=${WAT_PATH}/prod
#date
#INFILE=$CURRENTDIR/equil.namd
#charmrun ++remote-shell ssh ++verbose $NAMDHOME/namd2 +p$NP ++nodelist $NODELIST $INFILE >$CURRENTDIR/namd.log 2>$CURRENTDIR/namd.err
#date

#echo "Molecular dynamic simulation finished!"

#echo "Post processing of molecular dynamic data!"
#./run_post_process xs.cfg

#echo "Job finished!"
#\rm $NODELIST