#!/bin/bash
#PBS -S /bin/bash
#PBS -m e
#PBS -l nodes=1:ppn=4
#PBS -l walltime=72:00:00
##PBS -M yourname@buffalo.edu
#PBS -o test.out
#PBS -j oe
#PBS -N jobname
#PBS
#
# 
#
INFILE=$HOME/newtonRaphson/test.in
OUTFILE=$HOME/newtonRaphson/test.out
#
# generic setup and checks
#
# ulimit coredumpsize 0
# ulimit 
echo "check module commands:"
source $MODULESHOME/init/bash
limit coredumpsize 0

#which module
#module load charmm/c35b1r1-serial
#
# charmm binary
#
echo "Using newtonRaphson"
# NPROCS=`cat $PBS_NODEFILE | wc -l`
#
# goto dir from which job was submitted and run
#  (allows standard output to go to PBS output file)
#
cd $PBS_O_WORKDIR

# module load mpich/intel-10.1/ch_p4/1.2.7p1

date
$HOME/newtonRaphson/./newtonRaphson 1AON_frag1.pdb 1AON_frag2.pdb>$OUTFILE
date

#
# remove scratch directory
# \rm -r $PBSTMPDIR
